#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnLac.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DoAn")]
	public partial class DataClassesDoAnDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCustomer(Customer instance);
    partial void UpdateCustomer(Customer instance);
    partial void DeleteCustomer(Customer instance);
    partial void InsertOrderDetail(OrderDetail instance);
    partial void UpdateOrderDetail(OrderDetail instance);
    partial void DeleteOrderDetail(OrderDetail instance);
    partial void InsertOrder(Order instance);
    partial void UpdateOrder(Order instance);
    partial void DeleteOrder(Order instance);
    partial void InsertProduct(Product instance);
    partial void UpdateProduct(Product instance);
    partial void DeleteProduct(Product instance);
    partial void InsertAdmin(Admin instance);
    partial void UpdateAdmin(Admin instance);
    partial void DeleteAdmin(Admin instance);
    #endregion
		
		public DataClassesDoAnDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DoAnConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDoAnDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDoAnDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDoAnDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDoAnDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Customer> Customers
		{
			get
			{
				return this.GetTable<Customer>();
			}
		}
		
		public System.Data.Linq.Table<OrderDetail> OrderDetails
		{
			get
			{
				return this.GetTable<OrderDetail>();
			}
		}
		
		public System.Data.Linq.Table<Order> Orders
		{
			get
			{
				return this.GetTable<Order>();
			}
		}
		
		public System.Data.Linq.Table<Product> Products
		{
			get
			{
				return this.GetTable<Product>();
			}
		}
		
		public System.Data.Linq.Table<Admin> Admins
		{
			get
			{
				return this.GetTable<Admin>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Customers")]
	public partial class Customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _customerCode;
		
		private string _customerName;
		
		private string _customerEmail;
		
		private string _customerPassword;
		
		private string _customerPhone;
		
		private string _customerAddress;
		
		private System.Nullable<System.DateTime> _customerDateCreateOn;
		
		private EntitySet<Order> _Orders;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncustomerCodeChanging(int value);
    partial void OncustomerCodeChanged();
    partial void OncustomerNameChanging(string value);
    partial void OncustomerNameChanged();
    partial void OncustomerEmailChanging(string value);
    partial void OncustomerEmailChanged();
    partial void OncustomerPasswordChanging(string value);
    partial void OncustomerPasswordChanged();
    partial void OncustomerPhoneChanging(string value);
    partial void OncustomerPhoneChanged();
    partial void OncustomerAddressChanging(string value);
    partial void OncustomerAddressChanged();
    partial void OncustomerDateCreateOnChanging(System.Nullable<System.DateTime> value);
    partial void OncustomerDateCreateOnChanged();
    #endregion
		
		public Customer()
		{
			this._Orders = new EntitySet<Order>(new Action<Order>(this.attach_Orders), new Action<Order>(this.detach_Orders));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customerCode", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int customerCode
		{
			get
			{
				return this._customerCode;
			}
			set
			{
				if ((this._customerCode != value))
				{
					this.OncustomerCodeChanging(value);
					this.SendPropertyChanging();
					this._customerCode = value;
					this.SendPropertyChanged("customerCode");
					this.OncustomerCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customerName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string customerName
		{
			get
			{
				return this._customerName;
			}
			set
			{
				if ((this._customerName != value))
				{
					this.OncustomerNameChanging(value);
					this.SendPropertyChanging();
					this._customerName = value;
					this.SendPropertyChanged("customerName");
					this.OncustomerNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customerEmail", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string customerEmail
		{
			get
			{
				return this._customerEmail;
			}
			set
			{
				if ((this._customerEmail != value))
				{
					this.OncustomerEmailChanging(value);
					this.SendPropertyChanging();
					this._customerEmail = value;
					this.SendPropertyChanged("customerEmail");
					this.OncustomerEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customerPassword", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string customerPassword
		{
			get
			{
				return this._customerPassword;
			}
			set
			{
				if ((this._customerPassword != value))
				{
					this.OncustomerPasswordChanging(value);
					this.SendPropertyChanging();
					this._customerPassword = value;
					this.SendPropertyChanged("customerPassword");
					this.OncustomerPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customerPhone", DbType="NVarChar(24) NOT NULL", CanBeNull=false)]
		public string customerPhone
		{
			get
			{
				return this._customerPhone;
			}
			set
			{
				if ((this._customerPhone != value))
				{
					this.OncustomerPhoneChanging(value);
					this.SendPropertyChanging();
					this._customerPhone = value;
					this.SendPropertyChanged("customerPhone");
					this.OncustomerPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customerAddress", DbType="NVarChar(60)")]
		public string customerAddress
		{
			get
			{
				return this._customerAddress;
			}
			set
			{
				if ((this._customerAddress != value))
				{
					this.OncustomerAddressChanging(value);
					this.SendPropertyChanging();
					this._customerAddress = value;
					this.SendPropertyChanged("customerAddress");
					this.OncustomerAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customerDateCreateOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> customerDateCreateOn
		{
			get
			{
				return this._customerDateCreateOn;
			}
			set
			{
				if ((this._customerDateCreateOn != value))
				{
					this.OncustomerDateCreateOnChanging(value);
					this.SendPropertyChanging();
					this._customerDateCreateOn = value;
					this.SendPropertyChanged("customerDateCreateOn");
					this.OncustomerDateCreateOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Customer_Order", Storage="_Orders", ThisKey="customerCode", OtherKey="customerCode")]
		public EntitySet<Order> Orders
		{
			get
			{
				return this._Orders;
			}
			set
			{
				this._Orders.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Orders(Order entity)
		{
			this.SendPropertyChanging();
			entity.Customer = this;
		}
		
		private void detach_Orders(Order entity)
		{
			this.SendPropertyChanging();
			entity.Customer = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OrderDetails")]
	public partial class OrderDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _orderNumber;
		
		private int _productCode;
		
		private System.Nullable<int> _orderDetailsQuantity;
		
		private System.Nullable<decimal> _orderDetailsPriceEach;
		
		private EntityRef<Order> _Order;
		
		private EntityRef<Product> _Product;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnorderNumberChanging(int value);
    partial void OnorderNumberChanged();
    partial void OnproductCodeChanging(int value);
    partial void OnproductCodeChanged();
    partial void OnorderDetailsQuantityChanging(System.Nullable<int> value);
    partial void OnorderDetailsQuantityChanged();
    partial void OnorderDetailsPriceEachChanging(System.Nullable<decimal> value);
    partial void OnorderDetailsPriceEachChanged();
    #endregion
		
		public OrderDetail()
		{
			this._Order = default(EntityRef<Order>);
			this._Product = default(EntityRef<Product>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orderNumber", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int orderNumber
		{
			get
			{
				return this._orderNumber;
			}
			set
			{
				if ((this._orderNumber != value))
				{
					if (this._Order.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnorderNumberChanging(value);
					this.SendPropertyChanging();
					this._orderNumber = value;
					this.SendPropertyChanged("orderNumber");
					this.OnorderNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productCode", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int productCode
		{
			get
			{
				return this._productCode;
			}
			set
			{
				if ((this._productCode != value))
				{
					if (this._Product.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnproductCodeChanging(value);
					this.SendPropertyChanging();
					this._productCode = value;
					this.SendPropertyChanged("productCode");
					this.OnproductCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orderDetailsQuantity", DbType="Int")]
		public System.Nullable<int> orderDetailsQuantity
		{
			get
			{
				return this._orderDetailsQuantity;
			}
			set
			{
				if ((this._orderDetailsQuantity != value))
				{
					this.OnorderDetailsQuantityChanging(value);
					this.SendPropertyChanging();
					this._orderDetailsQuantity = value;
					this.SendPropertyChanged("orderDetailsQuantity");
					this.OnorderDetailsQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orderDetailsPriceEach", DbType="Decimal(19,4)")]
		public System.Nullable<decimal> orderDetailsPriceEach
		{
			get
			{
				return this._orderDetailsPriceEach;
			}
			set
			{
				if ((this._orderDetailsPriceEach != value))
				{
					this.OnorderDetailsPriceEachChanging(value);
					this.SendPropertyChanging();
					this._orderDetailsPriceEach = value;
					this.SendPropertyChanged("orderDetailsPriceEach");
					this.OnorderDetailsPriceEachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Order_OrderDetail", Storage="_Order", ThisKey="orderNumber", OtherKey="orderNumber", IsForeignKey=true)]
		public Order Order
		{
			get
			{
				return this._Order.Entity;
			}
			set
			{
				Order previousValue = this._Order.Entity;
				if (((previousValue != value) 
							|| (this._Order.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Order.Entity = null;
						previousValue.OrderDetails.Remove(this);
					}
					this._Order.Entity = value;
					if ((value != null))
					{
						value.OrderDetails.Add(this);
						this._orderNumber = value.orderNumber;
					}
					else
					{
						this._orderNumber = default(int);
					}
					this.SendPropertyChanged("Order");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Product_OrderDetail", Storage="_Product", ThisKey="productCode", OtherKey="productCode", IsForeignKey=true)]
		public Product Product
		{
			get
			{
				return this._Product.Entity;
			}
			set
			{
				Product previousValue = this._Product.Entity;
				if (((previousValue != value) 
							|| (this._Product.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Product.Entity = null;
						previousValue.OrderDetails.Remove(this);
					}
					this._Product.Entity = value;
					if ((value != null))
					{
						value.OrderDetails.Add(this);
						this._productCode = value.productCode;
					}
					else
					{
						this._productCode = default(int);
					}
					this.SendPropertyChanged("Product");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Orders")]
	public partial class Order : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _orderNumber;
		
		private System.Nullable<bool> _orderStatus;
		
		private System.Nullable<System.DateTime> _orderDate;
		
		private System.Nullable<System.DateTime> _orderShippedDate;
		
		private System.Nullable<int> _customerCode;
		
		private EntitySet<OrderDetail> _OrderDetails;
		
		private EntityRef<Customer> _Customer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnorderNumberChanging(int value);
    partial void OnorderNumberChanged();
    partial void OnorderStatusChanging(System.Nullable<bool> value);
    partial void OnorderStatusChanged();
    partial void OnorderDateChanging(System.Nullable<System.DateTime> value);
    partial void OnorderDateChanged();
    partial void OnorderShippedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnorderShippedDateChanged();
    partial void OncustomerCodeChanging(System.Nullable<int> value);
    partial void OncustomerCodeChanged();
    #endregion
		
		public Order()
		{
			this._OrderDetails = new EntitySet<OrderDetail>(new Action<OrderDetail>(this.attach_OrderDetails), new Action<OrderDetail>(this.detach_OrderDetails));
			this._Customer = default(EntityRef<Customer>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orderNumber", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int orderNumber
		{
			get
			{
				return this._orderNumber;
			}
			set
			{
				if ((this._orderNumber != value))
				{
					this.OnorderNumberChanging(value);
					this.SendPropertyChanging();
					this._orderNumber = value;
					this.SendPropertyChanged("orderNumber");
					this.OnorderNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orderStatus", DbType="Bit")]
		public System.Nullable<bool> orderStatus
		{
			get
			{
				return this._orderStatus;
			}
			set
			{
				if ((this._orderStatus != value))
				{
					this.OnorderStatusChanging(value);
					this.SendPropertyChanging();
					this._orderStatus = value;
					this.SendPropertyChanged("orderStatus");
					this.OnorderStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orderDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> orderDate
		{
			get
			{
				return this._orderDate;
			}
			set
			{
				if ((this._orderDate != value))
				{
					this.OnorderDateChanging(value);
					this.SendPropertyChanging();
					this._orderDate = value;
					this.SendPropertyChanged("orderDate");
					this.OnorderDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orderShippedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> orderShippedDate
		{
			get
			{
				return this._orderShippedDate;
			}
			set
			{
				if ((this._orderShippedDate != value))
				{
					this.OnorderShippedDateChanging(value);
					this.SendPropertyChanging();
					this._orderShippedDate = value;
					this.SendPropertyChanged("orderShippedDate");
					this.OnorderShippedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customerCode", DbType="Int")]
		public System.Nullable<int> customerCode
		{
			get
			{
				return this._customerCode;
			}
			set
			{
				if ((this._customerCode != value))
				{
					if (this._Customer.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncustomerCodeChanging(value);
					this.SendPropertyChanging();
					this._customerCode = value;
					this.SendPropertyChanged("customerCode");
					this.OncustomerCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Order_OrderDetail", Storage="_OrderDetails", ThisKey="orderNumber", OtherKey="orderNumber")]
		public EntitySet<OrderDetail> OrderDetails
		{
			get
			{
				return this._OrderDetails;
			}
			set
			{
				this._OrderDetails.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Customer_Order", Storage="_Customer", ThisKey="customerCode", OtherKey="customerCode", IsForeignKey=true)]
		public Customer Customer
		{
			get
			{
				return this._Customer.Entity;
			}
			set
			{
				Customer previousValue = this._Customer.Entity;
				if (((previousValue != value) 
							|| (this._Customer.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Customer.Entity = null;
						previousValue.Orders.Remove(this);
					}
					this._Customer.Entity = value;
					if ((value != null))
					{
						value.Orders.Add(this);
						this._customerCode = value.customerCode;
					}
					else
					{
						this._customerCode = default(Nullable<int>);
					}
					this.SendPropertyChanged("Customer");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_OrderDetails(OrderDetail entity)
		{
			this.SendPropertyChanging();
			entity.Order = this;
		}
		
		private void detach_OrderDetails(OrderDetail entity)
		{
			this.SendPropertyChanging();
			entity.Order = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Products")]
	public partial class Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _productCode;
		
		private string _productName;
		
		private string _productDescription;
		
		private int _productQuantityInStock;
		
		private System.Nullable<decimal> _productBuyPrice;
		
		private string _productImage;
		
		private System.Nullable<System.DateTime> _productCreateOn;
		
		private EntitySet<OrderDetail> _OrderDetails;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnproductCodeChanging(int value);
    partial void OnproductCodeChanged();
    partial void OnproductNameChanging(string value);
    partial void OnproductNameChanged();
    partial void OnproductDescriptionChanging(string value);
    partial void OnproductDescriptionChanged();
    partial void OnproductQuantityInStockChanging(int value);
    partial void OnproductQuantityInStockChanged();
    partial void OnproductBuyPriceChanging(System.Nullable<decimal> value);
    partial void OnproductBuyPriceChanged();
    partial void OnproductImageChanging(string value);
    partial void OnproductImageChanged();
    partial void OnproductCreateOnChanging(System.Nullable<System.DateTime> value);
    partial void OnproductCreateOnChanged();
    #endregion
		
		public Product()
		{
			this._OrderDetails = new EntitySet<OrderDetail>(new Action<OrderDetail>(this.attach_OrderDetails), new Action<OrderDetail>(this.detach_OrderDetails));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productCode", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int productCode
		{
			get
			{
				return this._productCode;
			}
			set
			{
				if ((this._productCode != value))
				{
					this.OnproductCodeChanging(value);
					this.SendPropertyChanging();
					this._productCode = value;
					this.SendPropertyChanged("productCode");
					this.OnproductCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string productName
		{
			get
			{
				return this._productName;
			}
			set
			{
				if ((this._productName != value))
				{
					this.OnproductNameChanging(value);
					this.SendPropertyChanging();
					this._productName = value;
					this.SendPropertyChanged("productName");
					this.OnproductNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productDescription", DbType="NVarChar(MAX)")]
		public string productDescription
		{
			get
			{
				return this._productDescription;
			}
			set
			{
				if ((this._productDescription != value))
				{
					this.OnproductDescriptionChanging(value);
					this.SendPropertyChanging();
					this._productDescription = value;
					this.SendPropertyChanged("productDescription");
					this.OnproductDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productQuantityInStock", DbType="Int NOT NULL")]
		public int productQuantityInStock
		{
			get
			{
				return this._productQuantityInStock;
			}
			set
			{
				if ((this._productQuantityInStock != value))
				{
					this.OnproductQuantityInStockChanging(value);
					this.SendPropertyChanging();
					this._productQuantityInStock = value;
					this.SendPropertyChanged("productQuantityInStock");
					this.OnproductQuantityInStockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productBuyPrice", DbType="Decimal(19,4)")]
		public System.Nullable<decimal> productBuyPrice
		{
			get
			{
				return this._productBuyPrice;
			}
			set
			{
				if ((this._productBuyPrice != value))
				{
					this.OnproductBuyPriceChanging(value);
					this.SendPropertyChanging();
					this._productBuyPrice = value;
					this.SendPropertyChanged("productBuyPrice");
					this.OnproductBuyPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productImage", DbType="VarChar(50)")]
		public string productImage
		{
			get
			{
				return this._productImage;
			}
			set
			{
				if ((this._productImage != value))
				{
					this.OnproductImageChanging(value);
					this.SendPropertyChanging();
					this._productImage = value;
					this.SendPropertyChanged("productImage");
					this.OnproductImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productCreateOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> productCreateOn
		{
			get
			{
				return this._productCreateOn;
			}
			set
			{
				if ((this._productCreateOn != value))
				{
					this.OnproductCreateOnChanging(value);
					this.SendPropertyChanging();
					this._productCreateOn = value;
					this.SendPropertyChanged("productCreateOn");
					this.OnproductCreateOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Product_OrderDetail", Storage="_OrderDetails", ThisKey="productCode", OtherKey="productCode")]
		public EntitySet<OrderDetail> OrderDetails
		{
			get
			{
				return this._OrderDetails;
			}
			set
			{
				this._OrderDetails.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_OrderDetails(OrderDetail entity)
		{
			this.SendPropertyChanging();
			entity.Product = this;
		}
		
		private void detach_OrderDetails(OrderDetail entity)
		{
			this.SendPropertyChanging();
			entity.Product = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Admin")]
	public partial class Admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AdminID;
		
		private string _AdminEmail;
		
		private string _AdminPassword;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAdminIDChanging(int value);
    partial void OnAdminIDChanged();
    partial void OnAdminEmailChanging(string value);
    partial void OnAdminEmailChanged();
    partial void OnAdminPasswordChanging(string value);
    partial void OnAdminPasswordChanged();
    #endregion
		
		public Admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AdminID
		{
			get
			{
				return this._AdminID;
			}
			set
			{
				if ((this._AdminID != value))
				{
					this.OnAdminIDChanging(value);
					this.SendPropertyChanging();
					this._AdminID = value;
					this.SendPropertyChanged("AdminID");
					this.OnAdminIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminEmail", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string AdminEmail
		{
			get
			{
				return this._AdminEmail;
			}
			set
			{
				if ((this._AdminEmail != value))
				{
					this.OnAdminEmailChanging(value);
					this.SendPropertyChanging();
					this._AdminEmail = value;
					this.SendPropertyChanged("AdminEmail");
					this.OnAdminEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminPassword", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string AdminPassword
		{
			get
			{
				return this._AdminPassword;
			}
			set
			{
				if ((this._AdminPassword != value))
				{
					this.OnAdminPasswordChanging(value);
					this.SendPropertyChanging();
					this._AdminPassword = value;
					this.SendPropertyChanged("AdminPassword");
					this.OnAdminPasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
