<?xml version="1.0" encoding="utf-8"?><Database Name="DoAn" Class="DataClassesDoAnDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;Initial Catalog=DoAn;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DoAnConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Customers" Member="Customers">
    <Type Name="Customer">
      <Column Name="customerCode" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="customerName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="customerEmail" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="customerPassword" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="customerPhone" Type="System.String" DbType="NVarChar(24) NOT NULL" CanBeNull="false" />
      <Column Name="customerAddress" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="customerDateCreateOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Customer_Order" Member="Orders" ThisKey="customerCode" OtherKey="customerCode" Type="Order" />
    </Type>
  </Table>
  <Table Name="dbo.OrderDetails" Member="OrderDetails">
    <Type Name="OrderDetail">
      <Column Name="orderNumber" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="productCode" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="orderDetailsQuantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="orderDetailsPriceEach" Type="System.Decimal" DbType="Decimal(19,4)" CanBeNull="true" />
      <Association Name="Order_OrderDetail" Member="Order" ThisKey="orderNumber" OtherKey="orderNumber" Type="Order" IsForeignKey="true" />
      <Association Name="Product_OrderDetail" Member="Product" ThisKey="productCode" OtherKey="productCode" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Orders" Member="Orders">
    <Type Name="Order">
      <Column Name="orderNumber" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="orderStatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="orderDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="orderShippedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="customerCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Order_OrderDetail" Member="OrderDetails" ThisKey="orderNumber" OtherKey="orderNumber" Type="OrderDetail" />
      <Association Name="Customer_Order" Member="Customer" ThisKey="customerCode" OtherKey="customerCode" Type="Customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Product">
      <Column Name="productCode" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="productName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="productDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="productQuantityInStock" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="productBuyPrice" Type="System.Decimal" DbType="Decimal(19,4)" CanBeNull="true" />
      <Column Name="productImage" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="productCreateOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Product_OrderDetail" Member="OrderDetails" ThisKey="productCode" OtherKey="productCode" Type="OrderDetail" />
    </Type>
  </Table>
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="AdminID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AdminEmail" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AdminPassword" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>